// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	provider2 "github.com/Wei-Shaw/sub2api/internal/adminplus/adapters/newapi/provider"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/adapters/providerrouter"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/adapters/sub2api/provider"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/actions"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/balances"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/bizlogs"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/channelchecks"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/costs"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/extension"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/health"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/mailverification"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/notifications"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/provisionjobs"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/proxy"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/purity"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/rates"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/scheduler"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/sessions"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/sitecatalog"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/sitediscovery"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/sub2api"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/suppliergroups"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/supplierkeys"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/suppliers"
	"github.com/Wei-Shaw/sub2api/internal/adminplus/app/usagecosts"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/handler/adminplus"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"net/http"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	authService := service.ProvideAdminPlusAuthService(client, userRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	billingCache := repository.NewBillingCache(redisClient)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	userPlatformQuotaRepository := repository.NewUserPlatformQuotaRepository(client)
	serviceUserPlatformQuotaRepository := repository.NewUserPlatformQuotaServiceAdapter(userPlatformQuotaRepository)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig, serviceUserPlatformQuotaRepository)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	dbDumper := repository.NewPgDumper(configConfig)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, totpService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	leaderLockCache := repository.NewLeaderLockCache(redisClient)
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, leaderLockCache, db, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	groupService := service.NewGroupService(groupRepository, apiKeyAuthCacheInvalidator)
	groupHandler := handler.ProvideAdminGroupHandler(groupService)
	opsRepository := repository.NewOpsRepository(db)
	businessLogRecorder := bizlogs.NewRecorder(opsRepository)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, configConfig)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	opsService := service.ProvideOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, opsSystemLogSink, settingService)
	settingHandler := handler.ProvideAdminSettingHandler(settingService, opsService, turnstileService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, groupHandler, settingHandler, opsHandler, systemHandler)
	readDB := sub2api.ProvideReadSQLDB(db, configConfig)
	sub2apiSQLRepository := sub2api.NewSQLRepository(readDB)
	credentialCipher := suppliers.UseCredentialCipher(secretEncryptor)
	sqlRepository := suppliers.NewSQLRepositoryWithCipher(db, readDB, credentialCipher)
	suppliersService := suppliers.NewService(sqlRepository)
	supplierHandler := adminplus.NewSupplierHandler(suppliersService)
	suppliergroupsSQLRepository := suppliergroups.NewSQLRepository(db)
	sessionsSQLRepository := sessions.NewSQLRepository(db)
	cipher := sessions.UseCipher(secretEncryptor)
	httpClient := provider.ProvideHTTPClient()
	sessionProfileClient := provider.NewSessionProfileClient(httpClient)
	providerClient := provider2.NewClient(httpClient)
	router := providerrouter.New(sessionProfileClient, providerClient)
	sessionsService := sessions.ProvideService(sessionsSQLRepository, cipher, suppliersService, router, router, router, businessLogRecorder)
	provisionjobsSQLRepository := provisionjobs.NewSQLRepository(db)
	streamPublisher := provisionjobs.NewStreamPublisher(redisClient)
	supplierkeysSQLRepository := supplierkeys.NewSQLRepository(db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	privacyClientFactory := service.ProvidePrivacyClientFactory()
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	proxyRuntimeConfig := proxy.RuntimeConfigFromConfig(configConfig)
	proxyRuntime := proxy.NewLocalMihomoRuntime(proxyRuntimeConfig)
	proxySQLRepository := proxy.NewSQLRepository(db)
	subscriptionNormalizer := proxy.NewSubscriptionNormalizer()
	proxySecretCipher := proxy.UseSecretCipher(secretEncryptor)
	proxyNodeCheckCache := proxy.ProvideNodeCheckCache(redisClient)
	proxyService := proxy.ProvideService(proxySQLRepository, proxySecretCipher, subscriptionNormalizer, proxyRuntime, proxyRuntimeConfig, proxyNodeCheckCache)
	billingService := service.NewBillingService(configConfig, pricingService)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.ProvideOpenAIOAuthService(proxyRepository, openAIOAuthClient, privacyClientFactory)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.NewChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	notificationEmailService := service.NewNotificationEmailService(settingRepository, emailService)
	balanceNotifyService := service.ProvideBalanceNotifyService(emailService, settingRepository, accountRepository, notificationEmailService)
	openAIGatewayService := service.NewOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, modelPricingResolver, channelService, balanceNotifyService, settingService, serviceUserPlatformQuotaRepository)
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, openAIGatewayService)
	sub2APIGateway := supplierkeys.UseSub2APIGateway(adminService, httpClient, configConfig)
	legacyAccountService := supplierkeys.UseLegacyAccountService(adminService)
	supplierkeysService := supplierkeys.NewServiceWithLegacy(supplierkeysSQLRepository, sessionsService, router, sub2APIGateway, legacyAccountService)
	costsSQLRepository := costs.NewSQLRepository(db)
	notificationsSQLRepository := notifications.NewSQLRepository(db)
	secretCipher := notifications.UseSecretCipher(secretEncryptor)
	notificationsService := notifications.NewServiceWithCipher(notificationsSQLRepository, secretCipher)
	suppliergroupsFeishuNotifier := suppliergroups.NewFeishuNotifier(notificationsService)
	suppliergroupsService := suppliergroups.NewServiceWithNotifier(suppliergroupsSQLRepository, suppliergroupsFeishuNotifier, sessionsService, router)
	mailVerificationSQLRepository := mailverification.NewSQLRepositoryWithCipher(db, secretEncryptor)
	googleOAuthSettingsProvider := mailverification.NewGoogleOAuthSettingsProvider(settingService)
	gmailProvider := mailverification.NewGmailProvider(httpClient, googleOAuthSettingsProvider)
	defaultTemplateClassifier := mailverification.NewDefaultTemplateClassifier()
	mailVerificationService := mailverification.ProvideService(mailVerificationSQLRepository, gmailProvider, defaultTemplateClassifier, emailService, businessLogRecorder)
	feishuNotifier := costs.NewFeishuNotifier(notificationsService)
	usagecostsSQLRepository := usagecosts.NewSQLRepository(db)
	usagecostsService := usagecosts.NewServiceWithDependencies(usagecostsSQLRepository, sessionsService, router)
	balancesSQLRepository := balances.NewSQLRepository(db)
	balancesFeishuNotifier := balances.NewFeishuNotifier(notificationsService)
	balanceCache := repository.NewAdminPlusBalanceCache(redisClient)
	balancesService := balances.ProvideService(balancesSQLRepository, balancesFeishuNotifier, sessionsService, router, sub2apiSQLRepository, balanceCache, businessLogRecorder)
	costsService := costs.NewServiceWithDependenciesAndNotifier(costsSQLRepository, feishuNotifier, sessionsService, router, router, usagecostsService, balancesService, suppliersService)
	channelchecksSQLRepository := channelchecks.NewSQLRepository(db)
	healthSQLRepository := health.NewSQLRepository(db)
	healthFeishuNotifier := health.NewFeishuNotifier(notificationsService)
	healthService := health.NewServiceWithNotifier(healthSQLRepository, healthFeishuNotifier)
	channelchecksService := channelchecks.NewServiceWithBindingEnsurer(channelchecksSQLRepository, suppliersService, sessionsService, healthService, supplierkeysService)
	provisionjobsService := provisionjobs.NewServiceWithDependencies(provisionjobsSQLRepository, streamPublisher, suppliergroupsService, supplierkeysService, costsService, channelchecksService)
	supplierGroupHandler := adminplus.NewSupplierGroupHandlerWithProvisionJobs(suppliergroupsService, provisionjobsService)
	supplierKeyHandler := adminplus.NewSupplierKeyHandlerWithProvisionJobs(supplierkeysService, provisionjobsService)
	provisionJobHandler := adminplus.NewProvisionJobHandler(provisionjobsService)
	ratesSQLRepository := rates.NewSQLRepository(db)
	ratesFeishuNotifier := rates.NewFeishuNotifier(notificationsService)
	ratesService := rates.NewServiceWithDependencies(ratesSQLRepository, ratesFeishuNotifier, sessionsService, router)
	rateHandler := adminplus.NewRateHandler(ratesService)
	balanceHandler := adminplus.NewBalanceHandler(balancesService)
	healthHandler := adminplus.NewHealthHandler(healthService)
	notificationHandler := adminplus.NewNotificationHandler(notificationsService)
	backupHandler := adminplus.NewBackupHandler(backupService, notificationsService, opsService, settingRepository)
	usageCostHandler := adminplus.NewUsageCostHandler(usagecostsService)
	channelCheckHandler := adminplus.NewChannelCheckHandlerWithProvisionJobs(channelchecksService, provisionjobsService)
	extensionSQLRepository := extension.NewSQLRepository(db)
	sessionCipher := extension.UseSessionCipher(secretEncryptor)
	sitediscoverySQLRepository := sitediscovery.NewSQLRepository(db)
	sitediscoveryCredentialCipher := sitediscovery.UseCredentialCipher(secretEncryptor)
	registrationProcessor := sitediscovery.ProvideRegistrationProcessor(sitediscoverySQLRepository, suppliersService, sitediscoveryCredentialCipher, businessLogRecorder, proxyService)
	ingestProcessor := extension.NewIngestProcessorWithCipher(ratesService, balancesService, healthService, usagecostsService, sessionsService, sessionCipher, registrationProcessor)
	extensionService := extension.ProvideService(extensionSQLRepository, ingestProcessor, suppliersService, businessLogRecorder)
	extensionHandler := adminplus.NewExtensionHandler(extensionService, suppliersService)
	sitediscoveryService := sitediscovery.ProvideService(sitediscoverySQLRepository, suppliersService, extensionService, mailVerificationService, router, sitediscoveryCredentialCipher, httpClient, businessLogRecorder, opsService, proxyService)
	siteDiscoveryHandler := adminplus.NewSiteDiscoveryHandler(sitediscoveryService)
	sitecatalogSQLRepository := sitecatalog.NewSQLRepository(db)
	sitecatalogService := sitecatalog.NewService(sitecatalogSQLRepository)
	siteCatalogHandler := adminplus.NewSiteCatalogHandler(sitecatalogService, sitediscoveryService)
	publicProxyAIHandler := adminplus.NewPublicProxyAIHandler(sitecatalogService, settingService)
	puritySQLRepository := purity.NewSQLRepository(db)
	purityService := purity.ProvideService(puritySQLRepository, accountRepository)
	purityHandler := adminplus.NewPurityHandler(purityService, settingService, turnstileService)
	mailVerificationHandler := adminplus.NewMailVerificationHandler(mailVerificationService)
	sessionHandler := adminplus.NewSessionHandler(sessionsService, balancesService)
	schedulerSQLRepository := scheduler.NewSQLRepository(db)
	schedulerService := scheduler.ProvideService(schedulerSQLRepository, suppliersService, extensionService, suppliergroupsService, ratesService, balancesService, healthService, usagecostsService, channelchecksService, sessionsService).WithCostSyncer(costsService)
	costHandler := adminplus.NewCostHandlerWithProvisionJobsAndScheduler(costsService, provisionjobsService, schedulerService)
	schedulerHandler := adminplus.NewSchedulerHandler(schedulerService)
	actionsSQLRepository := actions.NewSQLRepository(db)
	actionsService := actions.NewService(actionsSQLRepository)
	actionHandler := adminplus.NewActionHandler(actionsService)
	sub2APIRedis := sub2api.ProvideReadRedis(redisClient, configConfig)
	runtimeRepository := sub2api.NewRuntimeRepository(readDB, sub2APIRedis)
	sub2apiService := sub2api.NewService(sub2apiSQLRepository, runtimeRepository)
	proxyHandler := adminplus.NewProxyHandler(proxyService)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	accountTestService := service.NewAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService)
	sub2APIHandler := adminplus.NewSub2APIHandlerWithAccountTest(sub2apiService, accountTestService)
	adminPlusHandlers := handler.ProvideAdminPlusHandlers(supplierHandler, supplierGroupHandler, supplierKeyHandler, provisionJobHandler, rateHandler, balanceHandler, healthHandler, notificationHandler, usageCostHandler, costHandler, channelCheckHandler, extensionHandler, siteDiscoveryHandler, siteCatalogHandler, publicProxyAIHandler, purityHandler, mailVerificationHandler, sessionHandler, schedulerHandler, actionHandler, sub2APIHandler, proxyHandler, backupHandler)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo, notificationEmailService)
	handlers := handler.ProvideHandlers(authHandler, adminHandlers, adminPlusHandlers, handlerSettingHandler)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, settingService, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig, proxyRepository)
	channelMonitorRepository := repository.NewChannelMonitorRepository(client, db)
	channelMonitorService := service.ProvideChannelMonitorService(channelMonitorRepository, secretEncryptor)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, db, redisClient, configConfig, channelMonitorService, settingRepository, opsService)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	worker := provisionjobs.ProvideWorker(provisionjobsService)
	schedulerWorker := scheduler.ProvideWorker(schedulerService)
	v := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, emailQueueService, billingCacheService, backupService, idempotencyCoordinator, idempotencyCleanupService, sub2APIRedis, worker, schedulerWorker)
	application := &Application{
		Server:  httpServer,
		Cleanup: v,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	opsMetricsCollector *service.OpsMetricsCollector,
	opsAggregation *service.OpsAggregationService,
	opsAlertEvaluator *service.OpsAlertEvaluatorService,
	opsCleanup *service.OpsCleanupService,
	opsScheduledReport *service.OpsScheduledReportService,
	opsSystemLogSink *service.OpsSystemLogSink,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	backupService *service.BackupService,
	idempotencyCoordinator *service.IdempotencyCoordinator,
	idempotencyCleanup *service.IdempotencyCleanupService,
	sub2apiRedis sub2api.Sub2APIRedis,
	adminPlusProvisionWorker *provisionjobs.Worker,
	adminPlusScheduler *scheduler.Worker,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		type cleanupStep struct {
			name string
			fn   func() error
		}

		parallelSteps := []cleanupStep{
			{"OpsScheduledReportService", func() error {
				if opsScheduledReport != nil {
					opsScheduledReport.Stop()
				}
				return nil
			}},
			{"OpsCleanupService", func() error {
				if opsCleanup != nil {
					opsCleanup.Stop()
				}
				return nil
			}},
			{"OpsSystemLogSink", func() error {
				if opsSystemLogSink != nil {
					opsSystemLogSink.Stop()
				}
				return nil
			}},
			{"OpsAlertEvaluatorService", func() error {
				if opsAlertEvaluator != nil {
					opsAlertEvaluator.Stop()
				}
				return nil
			}},
			{"OpsAggregationService", func() error {
				if opsAggregation != nil {
					opsAggregation.Stop()
				}
				return nil
			}},
			{"OpsMetricsCollector", func() error {
				if opsMetricsCollector != nil {
					opsMetricsCollector.Stop()
				}
				return nil
			}},
			{"EmailQueueService", func() error {
				emailQueue.Stop()
				return nil
			}},
			{"BillingCacheService", func() error {
				billingCache.Stop()
				return nil
			}},
			{"BackupService", func() error {
				if backupService != nil {
					backupService.Stop()
				}
				return nil
			}},
			{"IdempotencyCleanupService", func() error {
				if idempotencyCleanup != nil {
					idempotencyCleanup.Stop()
				}
				return nil
			}},
			{"IdempotencyCoordinator", func() error {
				if idempotencyCoordinator != nil {
					service.SetDefaultIdempotencyCoordinator(nil)
				}
				return nil
			}},
			{"AdminPlusScheduler", func() error {
				if adminPlusScheduler != nil {
					adminPlusScheduler.Stop()
				}
				return nil
			}},
			{"AdminPlusProvisionWorker", func() error {
				if adminPlusProvisionWorker != nil {
					adminPlusProvisionWorker.Stop()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"Sub2APIReadonlyRedis", func() error {
				if !sub2apiRedis.Owned || sub2apiRedis.Client == nil {
					return nil
				}
				return sub2apiRedis.Client.Close()
			}},
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		runParallel := func(steps []cleanupStep) {
			var wg sync.WaitGroup
			for i := range steps {
				step := steps[i]
				wg.Add(1)
				go func() {
					defer wg.Done()
					if err := step.fn(); err != nil {
						log.Printf("[Cleanup] %s failed: %v", step.name, err)
						return
					}
					log.Printf("[Cleanup] %s succeeded", step.name)
				}()
			}
			wg.Wait()
		}

		runSequential := func(steps []cleanupStep) {
			for i := range steps {
				step := steps[i]
				if err := step.fn(); err != nil {
					log.Printf("[Cleanup] %s failed: %v", step.name, err)
					continue
				}
				log.Printf("[Cleanup] %s succeeded", step.name)
			}
		}

		runParallel(parallelSteps)
		runSequential(infraSteps)

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
}
