import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const componentPath = resolve(dirname(fileURLToPath(import.meta.url)), '../AppSidebar.vue')
const componentSource = readFileSync(componentPath, 'utf8')
const stylePath = resolve(dirname(fileURLToPath(import.meta.url)), '../../../style.css')
const styleSource = readFileSync(stylePath, 'utf8')

describe('AppSidebar Admin Plus navigation', () => {
  it('只展示 Admin Plus current 导航入口', () => {
    expect(componentSource).toContain("path: '/admin/dashboard'")
    expect(componentSource).toContain("path: '/admin/kanban'")
    expect(componentSource).toContain("path: '/admin/kanban/market-prices'")
    expect(componentSource).toContain("path: '/admin/kanban/supply-quality'")
    expect(componentSource).toContain("path: '/admin/kanban/profit'")
    expect(componentSource).toContain("path: '/admin/kanban/acceptance'")
    expect(componentSource).toContain("path: '/admin/kanban/events'")
    expect(componentSource).toContain("path: '/admin/kanban/settings'")
    expect(componentSource).toContain("path: '/admin/settings'")
    expect(componentSource).toContain("path: '/admin/suppliers'")
    expect(componentSource).toContain("path: '/admin/supplier-bindings'")
    expect(componentSource).toContain("path: '/admin/local-account-ops'")
    expect(componentSource).toContain("path: '/admin/supplier-rate-checks'")
    expect(componentSource).toContain("path: '/admin/account-rate-sync'")
    expect(componentSource).toContain("path: '/admin/scheduler'")
    expect(componentSource).toContain("path: '/admin/scheduler/routing-refill-history'")
    expect(componentSource).toContain("path: '/admin/actions'")
    expect(componentSource).toContain("path: '/admin/action-audits'")
    expect(componentSource).toContain("path: '/admin/collection/sessions'")
    expect(componentSource).toContain("path: '/admin/collection/site-discovery'")
    expect(componentSource).toContain("path: '/admin/mails'")
    expect(componentSource).toContain("path: '/admin/site-catalog'")
    expect(componentSource).toContain("path: '/admin/import-export'")
    expect(componentSource).toContain("path: '/admin/finance/costs'")
    expect(componentSource).toContain("path: '/admin/finance/usage-costs'")
    expect(componentSource).toContain("path: '/admin/finance/local-usage'")

    expect(componentSource).not.toContain("path: '/admin/users'")
    expect(componentSource).not.toContain("path: '/admin/accounts'")
    expect(componentSource).not.toContain("path: '/admin/channels'")
    expect(componentSource).not.toContain("path: '/admin/payment'")
    expect(componentSource).not.toContain("path: '/admin/events/announcements'")
    expect(componentSource).not.toContain("path: '/admin/operations/")
    expect(componentSource).not.toContain("path: '/admin/operations/extension-tasks'")
    expect(componentSource).not.toContain("path: '/admin/finance/billing'")
    expect(componentSource).not.toContain("path: '/admin/finance/reconciliation'")
    expect(componentSource).not.toContain("path: '/admin/ops'")
    expect(componentSource).not.toContain("path: '/admin/monitoring/balances'")
    expect(componentSource).not.toContain("path: '/admin/monitoring/rates'")
    expect(componentSource).not.toContain("path: '/admin/monitoring/health'")
    expect(componentSource).not.toContain("path: '/admin/monitoring/account-runtime'")
    expect(componentSource).not.toContain("path: '/admin/monitoring/announcements'")
    expect(componentSource).not.toContain("path: '/admin/automation/")
    expect(componentSource).not.toContain("label: '自动化'")
    expect(componentSource).not.toContain("label: '动作建议'")
    expect(componentSource).not.toContain("label: '通知记录'")
    expect(componentSource).not.toContain("label: '执行审计'")
    expect(componentSource).not.toContain("path: '/keys'")
    expect(componentSource).not.toContain("path: '/payment'")
  })

  it('将业务页面收敛到当前导航分组下', () => {
    const kanbanGroupMatch = componentSource.match(/label: '运营看板',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)
    const suppliersGroupMatch = componentSource.match(/label: '供应商',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)
    const collectionGroupMatch = componentSource.match(/label: '数据采集',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)
    const siteCatalogGroupMatch = componentSource.match(/label: '网址目录',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)
    const schedulerGroupMatch = componentSource.match(/label: '调度中心',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)
    const financeGroupMatch = componentSource.match(/label: '财务对账',[\s\S]*?children: \[([\s\S]*?)\n {4}\]/)

    expect(kanbanGroupMatch?.[1]).toContain("label: '市场价格'")
    expect(kanbanGroupMatch?.[1]).toContain("label: '供应质量'")
    expect(kanbanGroupMatch?.[1]).toContain("label: '模型利润'")
    expect(kanbanGroupMatch?.[1]).toContain("label: '接入验收'")
    expect(kanbanGroupMatch?.[1]).toContain("label: '价格事件'")
    expect(kanbanGroupMatch?.[1]).toContain("label: '设置'")
    expect(suppliersGroupMatch?.[1]).toContain("label: '供应商管理'")
    expect(suppliersGroupMatch?.[1]).toContain("label: '账号/Key 绑定'")
    expect(suppliersGroupMatch?.[1]).toContain("label: '本地账号运营'")
    expect(suppliersGroupMatch?.[1]).toContain("label: '倍率检测'")
    expect(suppliersGroupMatch?.[1]).toContain("label: '账号倍率同步'")
    expect(collectionGroupMatch?.[1]).toContain("label: '采集会话'")
    expect(collectionGroupMatch?.[1]).toContain("label: '渠道索引采集'")
    expect(collectionGroupMatch?.[1]).not.toContain("label: '插件任务'")
    expect(siteCatalogGroupMatch?.[1]).toContain("label: '站点列表'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '工作台'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '补池影响历史'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '通知中心'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '智能动作'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '操作审计'")
    expect(schedulerGroupMatch?.[1]).toContain("label: '导入/导出'")
    expect(componentSource).toContain("label: '运营看板'")
    expect(componentSource).not.toContain("label: '运营事件'")
    expect(componentSource).not.toContain("label: t('nav.ops')")
    expect(componentSource).not.toContain("label: '费率'")
    expect(componentSource).not.toContain("label: '余额'")
    expect(componentSource).not.toContain("label: '健康与并发'")
    expect(componentSource).not.toContain("label: '账号运行态'")
    expect(componentSource).not.toContain("label: '公告'")
    expect(financeGroupMatch?.[1]).toContain("label: '成本对账'")
    expect(financeGroupMatch?.[1]).toContain("label: '用量消耗'")
    expect(financeGroupMatch?.[1]).toContain("label: '本地用量'")
    expect(financeGroupMatch?.[1]).not.toContain("label: '供应商账单'")
    expect(financeGroupMatch?.[1]).not.toContain("label: '对账结果'")
  })

  it('二级导航在同组跳转后保持展开，点击同一级才关闭', () => {
    expect(componentSource).toContain('const expandedGroupPath = ref<string | null>(null)')
    expect(componentSource).toContain('const activeGroupPath = computed(() => {')
    expect(componentSource).toContain('expandedGroupPath.value = nextPath')
    expect(componentSource).toContain('@click="toggleNavGroup(item.path)"')
    expect(componentSource).toContain('isNavGroupExpanded(item.path)')
    expect(componentSource).toContain('expandedGroupPath.value === path')
    expect(componentSource).toContain('expandedGroupPath.value = null')
    expect(componentSource).toContain('@click="handleTopLevelLinkClick"')
    expect(componentSource).toContain('void router.push(path)')
    expect(componentSource).not.toContain('isNavGroupExpanded(item.path) || isNavItemActive(item)')
  })

  it('点击二级导航不清空展开状态，显式折叠侧栏才关闭二级导航', () => {
    const sublinkMatch = componentSource.match(/class="sidebar-sublink"[\s\S]*?@click="([^"]+)"/)
    const menuClickMatch = componentSource.match(/function handleMenuItemClick\(\) \{([\s\S]*?)\n\}/)
    const toggleSidebarMatch = componentSource.match(/function toggleSidebar\(\) \{([\s\S]*?)\n\}/)

    expect(sublinkMatch?.[1]).toBe('handleMenuItemClick')
    expect(menuClickMatch?.[1]).not.toContain('expandedGroupPath.value = null')
    expect(toggleSidebarMatch?.[1]).toContain('expandedGroupPath.value = null')
    expect(componentSource).toContain('function handleTopLevelLinkClick()')
  })
})

describe('AppSidebar header styles', () => {
  it('does not clip the version badge dropdown', () => {
    const sidebarHeaderBlockMatch = styleSource.match(/\.sidebar-header\s*\{[\s\S]*?\n {2}\}/)
    const sidebarBrandBlockMatch = componentSource.match(/\.sidebar-brand\s*\{[\s\S]*?\n\}/)

    expect(sidebarHeaderBlockMatch).not.toBeNull()
    expect(sidebarBrandBlockMatch).not.toBeNull()
    expect(sidebarHeaderBlockMatch?.[0]).not.toContain('@apply overflow-hidden;')
    expect(sidebarBrandBlockMatch?.[0]).not.toContain('overflow: hidden;')
  })
})
