package importexport

func defaultTableSpecs() []tableSpec {
	return []tableSpec{
		{
			Name:            "settings",
			ConflictColumns: []string{"key"},
			OrderColumns:    []string{"key"},
			OmitColumns:     []string{"id"},
			Description:     "系统键值配置",
		},
		{
			Name:            "groups",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "Sub2API 分组",
		},
		{
			Name:            "users",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "用户、角色、密码哈希和余额",
		},
		{
			Name:            "proxies",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "Sub2API 上游账号代理配置",
		},
		{
			Name:            "accounts",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "Sub2API 上游账号和凭据密文",
		},
		{
			Name:            "api_keys",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "用户 API Key",
		},
		{
			Name:            "account_groups",
			ConflictColumns: []string{"account_id", "group_id"},
			OrderColumns:    []string{"account_id", "group_id"},
			Description:     "账号和分组绑定",
		},
		{
			Name:            "channels",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "渠道配置",
		},
		{
			Name:            "channel_groups",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "渠道和分组绑定",
		},
		{
			Name:            "channel_model_pricing",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "渠道模型价格",
		},
		{
			Name:            "admin_plus_suppliers",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "Admin Plus 供应商档案",
		},
		{
			Name:            "admin_plus_supplier_accounts",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "供应商账号绑定",
		},
		{
			Name:            "admin_plus_supplier_groups",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "供应商分组",
		},
		{
			Name:            "admin_plus_supplier_keys",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "供应商 Key 绑定记录",
		},
		{
			Name:            "admin_plus_local_account_state_snapshots",
			ConflictColumns: []string{"local_sub2api_account_id"},
			OrderColumns:    []string{"local_sub2api_account_id"},
			Description:     "本地账号已采纳状态快照",
		},
		{
			Name:            "admin_plus_scheduler_plans",
			ConflictColumns: []string{"id"},
			OrderColumns:    []string{"id"},
			Description:     "调度计划",
		},
		{
			Name:            "admin_plus_scheduler_settings",
			ConflictColumns: []string{"key"},
			OrderColumns:    []string{"key"},
			Description:     "调度设置",
		},
		{
			Name:            "admin_plus_notification_settings",
			ConflictColumns: []string{"key"},
			OrderColumns:    []string{"key"},
			Description:     "通知中心设置",
		},
		{
			Name:            "admin_plus_site_discovery_settings",
			ConflictColumns: []string{"id"},
			OrderColumns:    []string{"id"},
			Description:     "渠道索引采集设置",
		},
		{
			Name:            "admin_plus_site_catalog_sites",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "网址目录站点",
		},
		{
			Name:            "admin_plus_site_catalog_links",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "网址目录链接",
		},
		{
			Name:            "admin_plus_site_catalog_categories",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "网址目录分类",
		},
		{
			Name:            "admin_plus_site_catalog_site_categories",
			ConflictColumns: []string{"site_id", "category_id"},
			OrderColumns:    []string{"site_id", "category_id"},
			Description:     "网址目录站点分类绑定",
		},
		{
			Name:            "admin_plus_site_catalog_tags",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "网址目录标签",
		},
		{
			Name:            "admin_plus_site_catalog_site_tags",
			ConflictColumns: []string{"site_id", "tag_id"},
			OrderColumns:    []string{"site_id", "tag_id"},
			Description:     "网址目录站点标签绑定",
		},
		{
			Name:            "admin_plus_site_catalog_sources",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "网址目录来源",
		},
		{
			Name:            "admin_plus_mail_credentials",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "邮箱验证码凭据密文",
		},
		{
			Name:            "admin_plus_proxy_subscriptions",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Sensitive:       true,
			Description:     "代理订阅密文",
		},
		{
			Name:            "admin_plus_proxy_policies",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "代理出口策略",
		},
		{
			Name:            "admin_plus_proxy_target_policies",
			ConflictColumns: []string{"id"},
			SequenceColumn:  "id",
			OrderColumns:    []string{"id"},
			Description:     "代理出口目标策略",
		},
	}
}

func excludedReason(tableName string) string {
	return excludedTableReasons()[tableName]
}

func excludedTableReasons() map[string]string {
	return map[string]string{
		"usage_logs":                                   "用量日志不属于核心迁移范围",
		"admin_plus_scheduler_runs":                    "调度运行历史属于运行态数据",
		"admin_plus_scheduler_steps":                   "调度步骤历史属于运行态数据",
		"admin_plus_scheduler_attempts":                "调度尝试历史属于运行态数据",
		"admin_plus_scheduler_actions":                 "动作建议可由运行信号重新生成",
		"admin_plus_routing_refill_runs":               "路由补池运行历史属于运行态数据",
		"admin_plus_extension_tasks":                   "浏览器插件任务属于运行态数据",
		"admin_plus_rate_snapshots":                    "倍率快照属于监控历史",
		"admin_plus_rate_change_events":                "倍率事件属于监控历史",
		"admin_plus_balance_snapshots":                 "余额快照属于监控历史",
		"admin_plus_balance_events":                    "余额事件属于监控历史",
		"admin_plus_health_samples":                    "健康采样属于监控历史",
		"admin_plus_health_events":                     "健康事件属于监控历史",
		"admin_plus_supplier_channel_check_snapshots":  "供应商渠道检测属于监控历史",
		"admin_plus_supplier_group_change_events":      "供应商分组变更属于审计历史",
		"admin_plus_supplier_funding_transactions":     "充值流水属于成本历史",
		"admin_plus_supplier_entitlement_transactions": "权益流水属于成本历史",
		"admin_plus_supplier_cost_ledger_entries":      "成本账本属于历史流水",
		"admin_plus_supplier_cost_snapshots":           "成本快照属于历史数据",
		"admin_plus_supplier_usage_cost_lines":         "用量消耗明细属于历史流水",
		"admin_plus_notification_deliveries":           "通知投递记录属于历史数据",
		"admin_plus_site_discovery_runs":               "渠道索引采集运行属于历史数据",
		"admin_plus_site_discoveries":                  "渠道索引候选属于采集过程数据",
		"admin_plus_supplier_registration_credentials": "注册任务凭据属于运行态数据",
		"admin_plus_site_catalog_metrics":              "网址目录指标属于监控历史",
		"admin_plus_supplier_browser_sessions":         "浏览器会话依赖本机加密和插件上下文",
		"admin_plus_proxy_config_versions":             "代理配置版本可由订阅重新生成",
		"admin_plus_proxy_nodes":                       "代理节点可由订阅重新生成",
		"admin_plus_proxy_runtime_slots":               "代理运行槽属于本机进程状态",
		"admin_plus_proxy_assignments":                 "代理分配属于运行态数据",
		"admin_plus_proxy_health_checks":               "代理健康检查属于监控历史",
		"admin_plus_proxy_audit_events":                "代理审计事件属于日志",
		"admin_plus_market_price_snapshots":            "市场价格快照属于运营历史",
		"admin_plus_cache_efficiency_snapshots":        "缓存效率快照属于运营历史",
		"admin_plus_supply_quality_snapshots":          "供应质量快照属于运营历史",
		"admin_plus_acceptance_reports":                "接入验收报告属于生成型证据历史",
		"admin_plus_kanban_events":                     "看板事件属于派生运营历史",
		"admin_plus_action_executions":                 "动作执行历史属于审计/运行态数据",
		"admin_plus_outbox_events":                     "Outbox 事件属于投递运行态数据",
		"admin_plus_account_rate_sync_history":         "账号倍率同步历史属于运行态数据",
		"admin_plus_purity_public_reports":             "公开纯度报告属于生成型历史",
		"admin_plus_announcement_events":               "公告事件属于运营历史",
	}
}
